### ISSUE TITLE
Recommendation: Include way of specifying which payment methods you want to show instead of avoid

### ISSUE THREAD

**Issue by hugoender** [j4imefoo/nokyc#18]
There are SO many payment methods and Robosats uses a text field where someone can put any payment method they want making the number of possible payment methods endless. Because of this, I would recommend letting the user specify which payment methods they want to show instead of which payment methods they want to avoid.

**Comment by j4imefoo** [comment]
It is a good idea, we though of it in the past. The problem is the majority of the people are interested in several and there is a real problem of missing some, since Bisq is adding new ones on a monthly basis. Each user, after correctly adjusting their filter, will mainly see the desired offers. 
Can definetelly revisit this in the future if it makes sense
